application:
  title: StoryTailor-SpringBoot
  version: 1.1.1

spring:
  application:
    name: storytailor

  security:
    enabled: false

  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://storytailor-db.c1dmi7dj6oou.ap-northeast-2.rds.amazonaws.com:5432/storytailor
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8008

flask:
  base-url: http://13.124.249.81:8083/tailor/

openai-service:
  api-key: ${OPEN_AI_API_KEY}
  api-url: https://api.openai.com/v1
  audio:
    path: /audio/transcriptions
    model: whisper-1
  img:
    edit-path: /images/edits
    generate-path: /images/generations

image:
  # upload-path: /img/upload
  upload-path: C:\img\upload
  base-url: http://13.124.249.81:8080/ # webserver port

http.pool:
  max.total: 200
  defaultMaxPerRoute: 100
  connection.timeout: 100000
  connection.request.timeout: 100000
  read.timeout: 100000
  validate.after.inactivity: 2000
