spring:
  application:
    name: storytailor

  security:
    enabled: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://storytailor-db.c1dmi7dj6oou.ap-northeast-2.rds.amazonaws.com:5432/storytailor
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 8008

genai:
  base: http://203.250.148.52:27580/genai/

openai-service:
  api-key: ${OPEN_AI_API_KEY}
  api-url: https://api.openai.com/v1
  audio:
    path: /audio/transcriptions
    model: whisper-1

image:
  upload-path: /img/upload
  base-url: http://13.124.249.81:8080/ # webserver port

http.pool:
  max.total: 200
  defaultMaxPerRoute: 100
  connection.timeout: 5000
  connection.request.timeout: 5000
  read.timeout: 10000
  validate.after.inactivity: 2000
